name = "calendar-workflow"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[workflows]]
name = "main-workflow"
binding = "MAIN_WORKFLOW"
class_name = "mainWorkflow"

[ai]
binding = "AI"

[triggers]
crons = ["0 19 * * 1-5"]

